#!/usr/bin/bash

awww query || awww-daemon

if [ -n "$1" ]; then
  if [[ $* == *--backwards* ]]; then
    awww img "$1" --transition-step 60 --transition-type grow --transition-pos 0.925,0.977 --transition-duration 2
  else
    awww img "$1" --transition-step 60 --transition-type outer --transition-pos 0.925,0.977 --transition-duration 2
  fi
fi
