term=foot
title=foot

#font=Cartograph Mono CF:size=14
#font=ProFont IIx Nerd Font:size=12
#font=CaskaydiaCove NF:size=14
#font=MapleMono NF Medium:size=14
#font=IBM EGA 8x14:size=19
#font=Departure Mono:size=14
#font=Terminess Nerd Font:size=14
#font=GohuFont 11 Nerd Font:size=13
#font=GohuFont 14 Nerd Font:size=13
#font=JetBrains Mono NF:size=14
#font=IBM VGA 8x16:size=19
#font=IBM Plex Mono:size=14
#font=NotoMono NF:size=14
#font=Monocraft:size=13
# font=B612 Mono:size=14
#font=CaskaydiaCove Nerd Font:size=10
font=CaskaydiaCove Nerd Font:weight=bold:size=10
line-height=15

pad=16x16

dpi-aware=yes

[cursor]
style=block
# blink=no
# blink-rate=500
# beam-thickness=1.5
# underline-thickness=<font underline thickness>

[colors-dark]
alpha=1.0
background=222436
foreground=CDD6F4

# black
regular0 = CDD6F4
bright0  = 585B70

# red
regular1 = F38BA8
bright1  = F38BA8

# green
regular2 = A6E3A1
bright2  = A6E3A1

# yellow
regular3 = F9E2AF
bright3  = F9E2AF

# blue
regular4 = 89B4FA
bright4  = 89B4FA

# magenta
regular5 = F5C2E7
bright5  = F5C2E7

# cyan
regular6 = 94E2D5
bright6  = 94E2D5

# white
regular7 = BAC2DE
bright7  = A6ADC8
